-- Operational state only. Closed by default; no business or identity seed data.
-- Trigger-level WHEN avoids nested CASE/END in D1 migration parsing; a missing gate stays closed.
CREATE TABLE migration_control (id INTEGER PRIMARY KEY CHECK(id=1), writes_enabled INTEGER NOT NULL CHECK(writes_enabled IN (0,1)));
INSERT INTO migration_control(id,writes_enabled) VALUES(1,0);
CREATE TRIGGER "fence_user_insert" BEFORE INSERT ON "user" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_user_update" BEFORE UPDATE ON "user" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_user_delete" BEFORE DELETE ON "user" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_session_insert" BEFORE INSERT ON "session" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_session_update" BEFORE UPDATE ON "session" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_session_delete" BEFORE DELETE ON "session" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_account_insert" BEFORE INSERT ON "account" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_account_update" BEFORE UPDATE ON "account" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_account_delete" BEFORE DELETE ON "account" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_verification_insert" BEFORE INSERT ON "verification" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_verification_update" BEFORE UPDATE ON "verification" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_verification_delete" BEFORE DELETE ON "verification" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_rateLimit_insert" BEFORE INSERT ON "rateLimit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_rateLimit_update" BEFORE UPDATE ON "rateLimit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_rateLimit_delete" BEFORE DELETE ON "rateLimit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_products_insert" BEFORE INSERT ON "products" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_products_update" BEFORE UPDATE ON "products" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_products_delete" BEFORE DELETE ON "products" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_product_variants_insert" BEFORE INSERT ON "product_variants" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_product_variants_update" BEFORE UPDATE ON "product_variants" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_product_variants_delete" BEFORE DELETE ON "product_variants" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_orders_insert" BEFORE INSERT ON "orders" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_orders_update" BEFORE UPDATE ON "orders" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_orders_delete" BEFORE DELETE ON "orders" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_user_profiles_insert" BEFORE INSERT ON "user_profiles" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_user_profiles_update" BEFORE UPDATE ON "user_profiles" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_user_profiles_delete" BEFORE DELETE ON "user_profiles" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_messages_insert" BEFORE INSERT ON "contact_messages" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_messages_update" BEFORE UPDATE ON "contact_messages" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_messages_delete" BEFORE DELETE ON "contact_messages" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_rate_limit_insert" BEFORE INSERT ON "contact_rate_limit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_rate_limit_update" BEFORE UPDATE ON "contact_rate_limit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
CREATE TRIGGER "fence_contact_rate_limit_delete" BEFORE DELETE ON "contact_rate_limit" WHEN (SELECT writes_enabled FROM migration_control WHERE id=1) IS NOT 1 BEGIN SELECT RAISE(ABORT,'Application writes are paused'); END;
